/**
 * Events API
 *
 * Contact: 97.amonsalve@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventoFiltroDto { 
    nombre?: string | null;
    ubicacion?: string | null;
    fechaHora?: string | null;
    capacidadMaxima?: number | null;
}

