/**
 * Events API
 *
 * Contact: 97.amonsalve@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Usuario } from './usuario';
import { Evento } from './evento';


export interface Inscripcion { 
    id?: number;
    usuarioId?: number;
    usuario?: Usuario;
    eventoId?: number;
    evento?: Evento;
    fechaInscripcion?: string;
}

