/**
 * Events API
 *
 * Contact: 97.amonsalve@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Evento } from './evento';
import { Inscripcion } from './inscripcion';


export interface Usuario { 
    id: number;
    nombre: string;
    correo: string;
    passwordHash: string;
    rol: string;
    eventosCreados?: Array<Evento> | null;
    inscripciones?: Array<Inscripcion> | null;
}

