/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Empresa } from './models/empresa';
export type { Evento } from './models/evento';
export type { EventoFiltroDto } from './models/evento-filtro-dto';
export type { FechasEventos } from './models/fechas-eventos';
export type { Inscripcion } from './models/inscripcion';
export type { LoginDto } from './models/login-dto';
export { Prioridad } from './models/prioridad';
export { Rol } from './models/rol';
export { TipoDocumento } from './models/tipo-documento';
export type { Usuario } from './models/usuario';
