/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthService } from './services/auth.service';
export { EventService } from './services/event.service';
export { InscripcionService } from './services/inscripcion.service';
export { UsuarioService } from './services/usuario.service';
