/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiEventEventosFiltradosGet$Params {
  Nombre?: string;
  Ubicacion?: string;
  FechaHora?: string;
  CapacidadMaxima?: number;
}

export function apiEventEventosFiltradosGet(http: HttpClient, rootUrl: string, params?: ApiEventEventosFiltradosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiEventEventosFiltradosGet.PATH, 'get');
  if (params) {
    rb.query('Nombre', params.Nombre, {});
    rb.query('Ubicacion', params.Ubicacion, {});
    rb.query('FechaHora', params.FechaHora, {});
    rb.query('CapacidadMaxima', params.CapacidadMaxima, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiEventEventosFiltradosGet.PATH = '/api/Event/eventos-filtrados';
