/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoDocumento } from '../models/tipo-documento';
export interface Empresa {
  indentificacionEmpresa?: string | null;
  nombreContactoEmpresa?: string | null;
  nombreEmpresa?: string | null;
  numeroContatoEmpresa?: string | null;
  tipoDocumento?: TipoDocumento;
}
