/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventoFiltroDto {
  capacidadMaxima?: number | null;
  fechaHora?: string | null;
  nombre?: string | null;
  ubicacion?: string | null;
}
