/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FechasEventos {
  fechaAprovacion?: string;
  fechaAprovacionFormato?: string | null;
  fechaAsignacion?: string;
  fechaAsignacionFormato?: string | null;
  fechaCotizacion?: string;
  fechaCotizacionFormato?: string | null;
  fechaFin?: string;
  fechaFinFormato?: string | null;
  fechaInicio?: string;
  fechaInicioFormato?: string | null;
}
