/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Evento } from '../models/evento';
import { Usuario } from '../models/usuario';
export interface Inscripcion {
  evento?: Evento;
  eventoId?: number;
  fechaInscripcion?: string;
  id?: number;
  usuario?: Usuario;
  usuarioId?: number;
}
