/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Evento } from '../models/evento';
import { Inscripcion } from '../models/inscripcion';
import { Rol } from '../models/rol';
import { TipoDocumento } from '../models/tipo-documento';
export interface Usuario {
  celularCorporativo: number;
  celularPersonal: number;
  correoCorporativo: string;
  correoPersonal: string;
  documentoIdentidad: number;
  empresa?: Empresa;
  eventosCreados?: Array<Evento> | null;
  fechaContratoFin?: string | null;
  fechaContratoInicio?: string | null;
  id: number;
  inscripciones?: Array<Inscripcion> | null;
  nombre: string;
  passwordHash: string;
  rol: Rol;
  tipoDocumento: TipoDocumento;
}
