/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUsuarioActualizarIdPut } from '../fn/usuario/api-usuario-actualizar-id-put';
import { ApiUsuarioActualizarIdPut$Params } from '../fn/usuario/api-usuario-actualizar-id-put';
import { apiUsuarioListarGet } from '../fn/usuario/api-usuario-listar-get';
import { ApiUsuarioListarGet$Params } from '../fn/usuario/api-usuario-listar-get';

@Injectable({ providedIn: 'root' })
export class UsuarioService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUsuarioListarGet()` */
  static readonly ApiUsuarioListarGetPath = '/api/Usuario/listar';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuarioListarGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuarioListarGet$Response(params?: ApiUsuarioListarGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUsuarioListarGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuarioListarGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsuarioListarGet(params?: ApiUsuarioListarGet$Params, context?: HttpContext): Observable<void> {
    return this.apiUsuarioListarGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUsuarioActualizarIdPut()` */
  static readonly ApiUsuarioActualizarIdPutPath = '/api/Usuario/actualizar/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsuarioActualizarIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsuarioActualizarIdPut$Response(params: ApiUsuarioActualizarIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUsuarioActualizarIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsuarioActualizarIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsuarioActualizarIdPut(params: ApiUsuarioActualizarIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiUsuarioActualizarIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
